# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tambah_mobil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFileDialog
import mysql.connector
import os
import menu_admin as mad
import shutil
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 679)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(24, 121, 202);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 280, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.lineEdit_stok = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_stok.setGeometry(QtCore.QRect(30, 380, 481, 31))
        self.lineEdit_stok.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_stok.setObjectName("lineEdit_stok")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(30, 40, 191, 31))
        self.lineEdit_id.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_tahun = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tahun.setGeometry(QtCore.QRect(30, 240, 481, 31))
        self.lineEdit_tahun.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_tahun.setObjectName("lineEdit_tahun")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_jenis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jenis.setGeometry(QtCore.QRect(30, 100, 481, 31))
        self.lineEdit_jenis.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_jenis.setObjectName("lineEdit_jenis")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 350, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.lineEdit_warna = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_warna.setGeometry(QtCore.QRect(30, 310, 481, 31))
        self.lineEdit_warna.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_warna.setObjectName("lineEdit_warna")
        self.lineEdit_type = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_type.setGeometry(QtCore.QRect(30, 170, 481, 31))
        self.lineEdit_type.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 490, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.pushButton_pilihfoto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pilihfoto.setGeometry(QtCore.QRect(210, 530, 93, 28))
        self.pushButton_pilihfoto.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.pushButton_pilihfoto.setObjectName("pushButton_pilihfoto")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(530, 40, 241, 481))
        self.listView.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.listView.setObjectName("listView")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 530, 141, 121))
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.lineEdit_harga = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_harga.setGeometry(QtCore.QRect(30, 450, 481, 31))
        self.lineEdit_harga.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_harga.setObjectName("lineEdit_harga")
        self.pushButton_keluar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_keluar.setGeometry(QtCore.QRect(660, 530, 111, 31))
        self.pushButton_keluar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(212, 17, 30);")
        self.pushButton_keluar.setObjectName("pushButton_keluar")
        self.pushButton_simpan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_simpan.setGeometry(QtCore.QRect(530, 530, 111, 31))
        self.pushButton_simpan.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.pushButton_simpan.setObjectName("pushButton_simpan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_pilihfoto.clicked.connect(self.images)


    def images(self):
        # Buka dialog untuk memilih gambar
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(None, "Select Image", "", "Images (*.png *.jpg *.jpeg *.bmp *.gif)", options=options)
        
        if file_name:
            # Menyimpan gambar ke folder tertentu
            saved_image_path = self.save_image(file_name)
            print(f"Gambar disimpan di: {saved_image_path}")
            
            # Menampilkan gambar yang dipilih
            pixmap = QPixmap(saved_image_path)
            if not pixmap.isNull():  # Periksa apakah gambar berhasil dimuat
                self.label.setPixmap(pixmap.scaled(200, 200, QtCore.Qt.KeepAspectRatio))  # Menampilkan gambar
                self.label.setText("")  # Menghapus teks default
            else:
                QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "Gagal memuat gambar.")

    def save_image(self, file_name):
        # Tentukan folder penyimpanan
        image_folder = 'profile'
        os.makedirs(image_folder, exist_ok=True)

        # Menyalin gambar ke folder
        base_name = os.path.basename(file_name)
        destination_path = os.path.join(image_folder, base_name)

        # Salin file gambar
        shutil.copy(file_name, destination_path)
        return destination_path
    

    def insert_mobil_data(self):
        # Ambil input dari field yang ada di GUI
        id_mbl = self.lineEdit_id.text()           # Ambil input dari field ID Mobil
        jenis_mbl = self.lineEdit_jenis.text()        # Ambil input dari field Jenis Mobil
        type_mbl = self.lineEdit_type.text()         # Ambil input dari field Tipe Mobil
        tahun_mbl = self.lineEdit_tahun.text()
        warna_mbl = self.lineEdit_warna.text()        # Ambil input dari field Warna Mobil
        stok_mbl = int(self.lineEdit_stok.text())    # Ambil input dari field Stok Mobil, pastikan konversi ke int
        harga_sewa_mbl = int(self.lineEdit_harga.text())

        try:
                # Koneksi ke database
                conn = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="uas"  # Ganti nama database sesuai kebutuhan
                )
                mycursor = conn.cursor()

                # Query SQL untuk memasukkan data
                sql = """
                INSERT INTO mobil (id_mbl, jenis_mbl, type_mbl, tahun_mbl, warna_mbl, stok_mbl, harga_sewa_mbl)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """
                val = (id_mbl, jenis_mbl, type_mbl, tahun_mbl, warna_mbl, stok_mbl, harga_sewa_mbl)
                mycursor.execute(sql, val)

                # Commit perubahan
                conn.commit()
                print("Data mobil berhasil ditambahkan...")

        except mysql.connector.Error as err:
                print(f"Error: {err}")

    def KembaliMenu(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = mad.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Warna :"))
        self.label_8.setText(_translate("MainWindow", "Tahun :"))
        self.label_6.setText(_translate("MainWindow", "Jenis :"))
        self.label_5.setText(_translate("MainWindow", "ID :"))
        self.label_7.setText(_translate("MainWindow", "Type :"))
        self.label_12.setText(_translate("MainWindow", "Stok :"))
        self.label_13.setText(_translate("MainWindow", "Foto Kendaraan :"))
        self.pushButton_pilihfoto.setText(_translate("MainWindow", "Pilih Foto"))
        self.label_10.setText(_translate("MainWindow", "Mobil"))
        self.label.setText(_translate("MainWindow", "image"))
        self.label_14.setText(_translate("MainWindow", "Harga :"))
        self.pushButton_keluar.setText(_translate("MainWindow", "Kembali"))
        self.pushButton_simpan.setText(_translate("MainWindow", "SIMPAN"))
        self.pushButton_simpan.clicked.connect(self.insert_mobil_data)
        self.pushButton_keluar.clicked.connect(self.KembaliMenu)
        self.pushButton_keluar.clicked.connect(MainWindow.close)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
