# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from user import User
import login as log



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(24, 121, 202);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 90, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kembali.setGeometry(QtCore.QRect(40, 500, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_kembali.setFont(font)
        self.pushButton_kembali.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(212, 17, 30);\n"
"")
        self.pushButton_kembali.setObjectName("pushButton_kembali")
        self.pushButton_regist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_regist.setGeometry(QtCore.QRect(610, 500, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_regist.setFont(font)
        self.pushButton_regist.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(6, 131, 35);")
        self.pushButton_regist.setObjectName("pushButton_regist")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 220, 571, 194))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_username_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username_3.setFont(font)
        self.lineEdit_username_3.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_username_3.setObjectName("lineEdit_username_3")
        self.gridLayout.addWidget(self.lineEdit_username_3, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_nama = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.gridLayout.addWidget(self.lineEdit_nama, 0, 1, 1, 1)
        self.lineEdit_nohp = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nohp.setFont(font)
        self.lineEdit_nohp.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_nohp.setObjectName("lineEdit_nohp")
        self.gridLayout.addWidget(self.lineEdit_nohp, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 140, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_regist.clicked.connect(self.BuatAkun)
        self.pushButton_kembali.clicked.connect(self.Kembali)
        self.pushButton_kembali.clicked.connect(MainWindow.close)

    def Kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def BuatAkun(self):
        nama = self.lineEdit_nama.text()
        alamat = self.lineEdit_username_3.text()
        no_hp = self.lineEdit_nohp.text()
        username = self.lineEdit_username.text()
        password = self.lineEdit_password.text()
        level = "penyewa"

        # Cek apakah ada field yang kosong
        if not (nama and alamat and no_hp and username and password):
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Semua field harus diisi!")
            return

        # Cek apakah no HP hanya berisi angka
        if not no_hp.isdigit():
            QtWidgets.QMessageBox.warning(None, "Peringatan", "Nomor HP harus berupa angka!")
            return

        # Jika semua validasi lulus, lakukan insert data
        User.insert_data(nama, alamat, no_hp, username, password, level)

        # Tampilkan notifikasi sukses
        QtWidgets.QMessageBox.information(None, "Sukses", "Akun berhasil dibuat!")

        # Kembali ke halaman login
        self.window = QtWidgets.QMainWindow()
        self.ui = log.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        # Tutup halaman registrasi
        self.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "REGISTRASI AKUN RENTAL JAYA"))
        self.pushButton_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.pushButton_regist.setText(_translate("MainWindow", "REGIST"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "Nama"))
        self.label_6.setText(_translate("MainWindow", "Alamat"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "No HP"))
        self.label_4.setText(_translate("MainWindow", "Silahkan lengkapi datanya"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
