# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'struk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QMessageBox
import menu_struk as st


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(24, 121, 202);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 100, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 160, 131, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit.setObjectName("lineEdit")
        self.cari = QtWidgets.QPushButton(self.centralwidget)
        self.cari.setGeometry(QtCore.QRect(260, 160, 91, 41))
        self.cari.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.cari.setObjectName("pushButton")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 450, 281, 31))
        self.lineEdit_5.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(110, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 280, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 220, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 310, 281, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(110, 350, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 240, 281, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 202, 111);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 380, 281, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(480, 240, 281, 31))
        self.lineEdit_6.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"background-color: rgb(255, 202, 111);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(550, 190, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 490, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(22, 22, 22);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(6, 131, 35);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.kembali = QtWidgets.QPushButton(self.centralwidget)
        self.kembali.setGeometry(QtCore.QRect(50, 20, 93, 28))
        self.kembali.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(212, 17, 30);")
        self.kembali.setObjectName("kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.cari.clicked.connect(self.search_data)
        self.pushButton_2.clicked.connect(self.display_data_popup)

        self.kembali.clicked.connect(self.Struk)
        self.kembali.clicked.connect(MainWindow.close)



    def Struk(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = st.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def search_data(self):
        id_transaksi = self.lineEdit.text()

        try:
            # Connect to the database
            conn = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="uas"
            )
            cursor = conn.cursor()

            # Execute the query to get data from motor and pembayaran_motor
            query = """
                SELECT m.jenis_mtr, m.type_mtr, m.tahun_mtr, m.warna_mtr, pm.total_pembayaran
                FROM motor m
                JOIN pembayaran_motor pm ON m.id_mtr = pm.id_transaksi_motor
                WHERE m.id_mtr = %s
            """
            cursor.execute(query, (id_transaksi,))
            result = cursor.fetchone()

            if result:
                # Populate the QLineEdits with the result
                self.lineEdit_2.setText(result[0])  # jenis_mtr
                self.lineEdit_3.setText(result[1])  # type_mtr
                self.lineEdit_4.setText(str(result[2]))  # tahun_mtr
                self.lineEdit_5.setText(result[3])  # warna_mtr
                self.lineEdit_6.setText(str(result[4]))  # total_pembayaran
            else:
                QtWidgets.QMessageBox.warning(
                    None, "Data Not Found", "ID transaksi tidak ditemukan.")

            cursor.close()
            conn.close()

        except mysql.connector.Error as err:
            QtWidgets.QMessageBox.critical(
                None, "Database Error", f"Terjadi kesalahan: {err}")
        
    def display_data_popup(self):
        # Ambil data dari QLineEdit
        jenis_mtr = self.lineEdit_2.text()
        type_mtr = self.lineEdit_3.text()
        tahun_mtr = self.lineEdit_4.text()
        warna_mtr = self.lineEdit_5.text()
        total_pembayaran = self.lineEdit_6.text()

        # Format data menjadi string untuk ditampilkan
        data_message = f"""
        Jenis Motor: {jenis_mtr}
        Tipe Motor: {type_mtr}
        Tahun Motor: {tahun_mtr}
        Warna Motor: {warna_mtr}
        Total Pembayaran: {total_pembayaran}
        """

        # Buat pop-up dengan QMessageBox
        QMessageBox.information(None, "Data Transaksi", data_message)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Struk"))
        self.label_5.setText(_translate("MainWindow", "Terimakasih Atas Kunjungan Anda"))
        self.label_9.setText(_translate("MainWindow", "Warna"))
        self.label_7.setText(_translate("MainWindow", "Type"))
        self.label_6.setText(_translate("MainWindow", "Jenis "))
        self.label_8.setText(_translate("MainWindow", "Tahun"))
        self.label_10.setText(_translate("MainWindow", "ID"))
        self.label_11.setText(_translate("MainWindow", "Total Pembayaran"))
        self.pushButton_2.setText(_translate("MainWindow", "Oke"))
        self.cari.setText(_translate("MainWindow", "CARI"))
        self.kembali.setText(_translate("Mainwindow","KEMBALI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
